[package]
name = "luaasm"
version = "0.1.0"
authors = ["Yuze Fu <i@xfox.me>"]
edition = "2018"

[dependencies]
pest = "2.0.2"
clap = "2.32.0"
pest_derive = "2.0.1"
serde_json = "1.0.33"
serde = "1.0.81"
serde_derive = "1.0.81"
lazy_static = "1.2.0"
